/*
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef ENUM_LIST_H
#define ENUM_LIST_H
#include "native_buffer.h"

int32_t g_nativeBufferColorSpace[] = {
    OH_COLORSPACE_NONE,
    OH_COLORSPACE_BT601_EBU_FULL,
    OH_COLORSPACE_BT601_SMPTE_C_FULL,
    OH_COLORSPACE_BT709_FULL,
    OH_COLORSPACE_BT2020_HLG_FULL,
    OH_COLORSPACE_BT2020_PQ_FULL,
    OH_COLORSPACE_BT601_EBU_LIMIT,
    OH_COLORSPACE_BT601_SMPTE_C_LIMIT,
    OH_COLORSPACE_BT709_LIMIT,
    OH_COLORSPACE_BT2020_HLG_LIMIT,
    OH_COLORSPACE_BT2020_PQ_LIMIT,
    OH_COLORSPACE_SRGB_FULL,
    OH_COLORSPACE_P3_FULL,
    OH_COLORSPACE_P3_HLG_FULL,
    OH_COLORSPACE_P3_PQ_FULL,
    OH_COLORSPACE_ADOBERGB_FULL,
    OH_COLORSPACE_SRGB_LIMIT,
    OH_COLORSPACE_SRGB_LIMIT,
    OH_COLORSPACE_P3_HLG_LIMIT,
    OH_COLORSPACE_P3_PQ_LIMIT,
    OH_COLORSPACE_ADOBERGB_LIMIT,
    OH_COLORSPACE_LINEAR_SRGB,
    OH_COLORSPACE_LINEAR_BT709,
    OH_COLORSPACE_LINEAR_P3,
    OH_COLORSPACE_LINEAR_BT2020,
    OH_COLORSPACE_DISPLAY_SRGB,
    OH_COLORSPACE_DISPLAY_P3_SRGB,
    OH_COLORSPACE_DISPLAY_P3_HLG,
    OH_COLORSPACE_DISPLAY_P3_PQ,
    OH_COLORSPACE_DISPLAY_BT2020_SRGB,
    OH_COLORSPACE_DISPLAY_BT2020_HLG,
    OH_COLORSPACE_DISPLAY_BT2020_PQ
};

int32_t g_nativeBufferFormat[] = {
    NATIVEBUFFER_PIXEL_FMT_CLUT8 = 0,
    NATIVEBUFFER_PIXEL_FMT_CLUT1,
    NATIVEBUFFER_PIXEL_FMT_CLUT4,
    NATIVEBUFFER_PIXEL_FMT_RGB_565 = 3,
    NATIVEBUFFER_PIXEL_FMT_RGBA_5658,
    NATIVEBUFFER_PIXEL_FMT_RGBX_4444,
    NATIVEBUFFER_PIXEL_FMT_RGBA_4444,
    NATIVEBUFFER_PIXEL_FMT_RGB_444,
    NATIVEBUFFER_PIXEL_FMT_RGBX_5551,
    NATIVEBUFFER_PIXEL_FMT_RGBA_5551,
    NATIVEBUFFER_PIXEL_FMT_RGB_555,
    NATIVEBUFFER_PIXEL_FMT_RGBX_8888,
    NATIVEBUFFER_PIXEL_FMT_RGBA_8888,
    NATIVEBUFFER_PIXEL_FMT_RGB_888,
    NATIVEBUFFER_PIXEL_FMT_BGR_565,
    NATIVEBUFFER_PIXEL_FMT_BGRX_4444,
    NATIVEBUFFER_PIXEL_FMT_BGRA_4444,
    NATIVEBUFFER_PIXEL_FMT_BGRX_5551,
    NATIVEBUFFER_PIXEL_FMT_BGRA_5551,
    NATIVEBUFFER_PIXEL_FMT_BGRX_8888,
    NATIVEBUFFER_PIXEL_FMT_BGRA_8888
    NATIVEBUFFER_PIXEL_FMT_YUV_422_I,
    NATIVEBUFFER_PIXEL_FMT_YCBCR_422_SP,
    NATIVEBUFFER_PIXEL_FMT_YCRCB_422_SP,
    NATIVEBUFFER_PIXEL_FMT_YCBCR_420_SP,
    NATIVEBUFFER_PIXEL_FMT_YCRCB_420_SP,
    NATIVEBUFFER_PIXEL_FMT_YCBCR_422_P,
    NATIVEBUFFER_PIXEL_FMT_YCRCB_422_P,
    NATIVEBUFFER_PIXEL_FMT_YCBCR_420_P,
    NATIVEBUFFER_PIXEL_FMT_YCRCB_420_P,
    NATIVEBUFFER_PIXEL_FMT_YUYV_422_PKG,
    NATIVEBUFFER_PIXEL_FMT_UYVY_422_PKG,
    NATIVEBUFFER_PIXEL_FMT_YVYU_422_PKG,
    NATIVEBUFFER_PIXEL_FMT_VYUY_422_PKG,
    NATIVEBUFFER_PIXEL_FMT_RGBA_1010102,
    NATIVEBUFFER_PIXEL_FMT_YCBCR_P010,
    NATIVEBUFFER_PIXEL_FMT_YCRCB_P010,
    NATIVEBUFFER_PIXEL_FMT_RAW10,
    NATIVEBUFFER_PIXEL_FMT_VENDER_MASK,
    NATIVEBUFFER_PIXEL_FMT_BUTT
};

int32_t g_nativeBufferMetadataType[] = {
    OH_VIDEO_HDR_HLG,
    OH_VIDEO_HDR_HDR10,
    OH_VIDEO_HDR_VIVID
};

#endif